
spring.application.name=usuario-servicio


server.port=8081

spring.datasource.url=jdbc:postgresql://ep-dark-sky-apfaakt0-pooler.c-7.us-east-1.aws.neon.tech/karubag_usuario?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dmQA03ekBjYq
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
