 #===================================================================
# Identidad del microservicio
# ===================================================================
spring.application.name=usuario-servicio

# ===================================================================
# Servidor HTTP
# ===================================================================
server.port=8081

# ===================================================================
# Conexión a Base de Datos (Neon PostgreSQL en la nube)
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-dark-sky-apfaakt0-pooler.c-7.us-east-1.aws.neon.tech/karubag_usuario?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dmQA03ekBjYq
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA / Hibernate (estrategia Code-First)
# ===================================================================
# update = Hibernate crea las tablas si no existen, sin borrar datos
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en consola (útil para aprender y debuggear)
spring.jpa.show-sql=true

# Formatear el SQL para que sea legible en los logs
spring.jpa.properties.hibernate.format_sql=true

# Dialect específico de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect